

spring:
  application:
    name: Spring_AI

  data:
    mongodb:
      uri: ${MONGODB_URI}
      auto-index-creation: true
    redis:
      url: ${REDIS_URI}

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: study-plan-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.springAi.*"


  gemini:
    api-keys: ${GEMINI_API_KEYS}
    model: gemini-2.5-flash


