spring.application.name=Spring_AI
spring.ai.openai.base-url=https://openrouter.ai/api

spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.openai.chat.options.model=openai/gpt-oss-120b:free
spring.ai.google.genai.chat.options.model=gemini-2.5-flash-lite
#gemini-2.5-flash